# Generated by Django 5.1.1 on 2024-09-09 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Papel_pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Status_rfid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='CorRFID_Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corRFID', models.CharField(max_length=15)),
                ('cod_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.papel_pessoa')),
            ],
        ),
        migrations.CreateModel(
            name='Rfid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_rfid_value', models.CharField(max_length=12, unique=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('data_desativacao', models.DateTimeField(editable=False)),
                ('vinculado', models.BooleanField()),
                ('cod_corRFID_funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.corrfid_funcao')),
                ('cod_Status_rfid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.status_rfid')),
            ],
        ),
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('sobrenome', models.CharField(max_length=35)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField()),
                ('idade', models.IntegerField()),
                ('vinculado', models.BooleanField()),
                ('cod_Papel_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.papel_pessoa')),
                ('cod_Rfid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.rfid', unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Historico_acesso_campus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_acesso', models.DateTimeField(auto_now_add=True)),
                ('funcao_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.papel_pessoa')),
                ('cod_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.pessoa')),
                ('cod_rfid', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.rfid')),
            ],
        ),
        migrations.CreateModel(
            name='Usuario_sistema',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_de_usuario', models.CharField(max_length=20)),
                ('usuario', models.CharField(max_length=15)),
                ('senha', models.CharField(max_length=30)),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('cod_pessoa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.pessoa', unique=True)),
            ],
        ),
    ]
