# Generated by Django 5.1.1 on 2024-09-09 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_controle_ifto', '0002_alter_pessoa_cod_papel_pessoa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papel_pessoa',
            name='descricao',
            field=models.CharField(max_length=25),
        ),
    ]
