# Generated by Django 5.1.1 on 2024-09-09 02:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_controle_ifto', '0003_alter_papel_pessoa_descricao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cod_Papel_pessoa',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.papel_pessoa'),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='idade',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='rfid',
            name='data_desativacao',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
