# Generated by Django 5.1.1 on 2024-09-09 02:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_controle_ifto', '0004_alter_pessoa_cod_papel_pessoa_alter_pessoa_idade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cod_Rfid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.rfid', unique=True),
        ),
    ]
