# Generated by Django 5.1.1 on 2024-09-09 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_controle_ifto', '0005_alter_pessoa_cod_rfid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rfid',
            name='data_desativacao',
            field=models.DateTimeField(),
        ),
    ]
