# Generated by Django 5.1.1 on 2024-09-09 03:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_controle_ifto', '0007_alter_pessoa_idade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='cod_Rfid',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.rfid'),
        ),
        migrations.AlterField(
            model_name='usuario_sistema',
            name='cod_pessoa',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.pessoa'),
        ),
    ]
