# Generated by Django 5.1.1 on 2024-09-09 03:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_controle_ifto', '0008_alter_pessoa_cod_rfid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='corrfid_funcao',
            name='cod_cargo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.papel_pessoa'),
        ),
    ]
