# Generated by Django 5.1.1 on 2024-09-11 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerenciar_controle_ifto', '0009_alter_corrfid_funcao_cod_cargo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rfid',
            name='cod_Status_rfid',
        ),
        migrations.AddField(
            model_name='rfid',
            name='ativo',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rfid',
            name='motivo_desativacao',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='corrfid_funcao',
            name='corRFID',
            field=models.CharField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='cod_Rfid',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, to='gerenciar_controle_ifto.rfid'),
        ),
        migrations.DeleteModel(
            name='Status_rfid',
        ),
    ]
